### ISSUE TITLE
Changing topics onmessage fails

### ISSUE THREAD

**Issue by alarinel** [lahsivjar/react-stomp#150]
If on the render I change topics then with debug enabled it shows it unsubscribe the old topic and add the new one instead but all subsequent events show up as unhandled. They are handled perfectly fine until the topic changes.

**Comment by wejrox** [comment]
Seconding this, I'm using this for conditionally rendering based on a setting the user can mutate. The only way around that I've found so far is to have two sockjsclient components be conditionally rendered based on whether the topic has changed, which forces a new component to be created instead of just changing the props.

**Comment by lahsivjar** [comment]
Fixed by #180
