### ISSUE TITLE
How to clean up using React Functional Component ?

### ISSUE THREAD

**Issue by Moshiour027** [lahsivjar/react-stomp#163]
A guideline about how we cleanup socket connection when we are using functional component will be helpful. 

Thanks

**Comment by aminmc** [comment]
The author can correct me if I'm wrong but when your functional component unmounts then the SockJsClient will disconnect automatically. If you enable debug on your SockJsClient you'll see the disconnection happening. Is this what you are looking for? 
For example the below screen shot happens when i naviagte away from the functional component that has the SockJsClient:

![Screenshot 2020-06-24 at 07 56 01](https://user-images.githubusercontent.com/290639/85511128-2f62bd00-b5f0-11ea-8b89-4c5a5c599ec3.png)

**Comment by Moshiour027** [comment]
So we do not need to take any actions there ... :)

**Comment by lahsivjar** [comment]
Closing the issue, reopen if needed
